[workspace]
members = ["cli", "core"]

[workspace.package]
version = "0.1.0"
authors = ["Łukasz Gmys"]
description = "Fake documents generator for Elasticsearch"
documentation = "https://github.com/lgmys/fakebeat"
